BurgerApp/BurgerApp.WebApp/Controllers/BurgerController.cs
using BurgerApp.Dto.ViewModels;
using BurgerApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.WebApp.Controllers
{
    [Route("")]
    public class BurgerController : Controller
    {
        private readonly IBurgerService _burgerService;

        public BurgerController(IBurgerService burgerService)
        {
            _burgerService = burgerService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var burgers = _burgerService.GetAllBurgers();
            return View(burgers);
        }
        [HttpPost("remove")]
        public IActionResult Remove(int id)
        {
            _burgerService.RemoveBurger(id);
            return RedirectToAction("Index");
        }
        [HttpGet("add")]
        public IActionResult AddBurger()
        {
            return View("AddBurger");
        }
        [HttpPost("add")]
        public IActionResult AddBurger(CreateBurgerVM createBurgerVM)
        {
            _burgerService.AddBurger(createBurgerVM);
            return RedirectToAction("Index");
        }

        [HttpGet("edit/{id}")]
        public IActionResult EditBurger(int id)
        {
            var burger = _burgerService.GetBurger(id);
            if (burger == null)
            {
                return NotFound(); 
            }

            var editBurgerVM = new EditBurgerVM
            {
                Id = burger.Id,
            };

            return View(editBurgerVM);
        }



        [HttpPost("edit/{id}")]
        public IActionResult EditBurger(EditBurgerVM editBurgerVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _burgerService.EditBurger(editBurgerVM, editBurgerVM.Id);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError("", "An error occurred while updating the burger.");
                }
            }

            return View("EditBurger", editBurgerVM);
        }
    }
}

BurgerApp/BurgerApp.WebApp/Controllers/LocationController.cs
using BurgerApp.Dto.ViewModels;
using BurgerApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.WebApp.Controllers
{
    [Route("location")]
    public class LocationController : Controller
    {
        private readonly ILocationService _locationService;
        public LocationController(ILocationService locationService)
        {
            _locationService = locationService;
        }
        [HttpGet("")]
        public IActionResult Index()
        {
            var locations = _locationService.GetAllLocations();
            return View(locations);
        }
        [HttpPost("remove")]
        public IActionResult Remove(int id)
        {
            _locationService.RemoveLocation(id);
            return RedirectToAction("Index");
        }
        [HttpGet("add")]
        public IActionResult AddLocation()
        {
            return View("AddLocation");
        }
        [HttpPost("add")]
        public IActionResult AddLocation(CreateLocationVM createLocationVM)
        {
            _locationService.AddLocation(createLocationVM);
            return RedirectToAction("Index");
        }
        [HttpGet("edit/{id}")]
        public IActionResult EditLocation(int id)
        {
            var location = _locationService.GetLocation(id);
            if(location == null)
            {
                return NotFound();
            }
            var editLocation = new EditLocationVM
            {
                Id = location.Id
            };
            return View(editLocation);
        }
        [HttpPost("edit/{id}")]
        public IActionResult EditLocation(EditLocationVM editLocationVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _locationService.EditLocation(editLocationVM, editLocationVM.Id);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "An error occurred while updating the location.");

                }
            }
            return View("EditLocation", editLocationVM);
        }
    }
}

BurgerApp/BurgerApp.WebApp/Controllers/OrderController.cs
using BurgerApp.Dto.ViewModels;
using BurgerApp.Services;
using BurgerApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BurgerApp.WebApp.Controllers
{
    [Route("order")]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ILocationService _locationService;
        private readonly IBurgerService _burgerService;
        public OrderController(IOrderService orderService, ILocationService locationService,IBurgerService burgerService)
        {
            _orderService = orderService;
            _locationService = locationService;
            _burgerService = burgerService;
        }
        [HttpGet("")]
        public IActionResult Index()
        {
            var orders = _orderService.GetAllOrders();
            return View(orders);
        }
        [HttpPost("remove")]
        public IActionResult Remove(int id)
        {
            _orderService.RemoveOrder(id);
            return RedirectToAction("Index");
        }
        [HttpPost("deliver")]
        public IActionResult OrderDelivered(int id)
        {
            _orderService.OrderIsDelivered(id);
            return RedirectToAction("Index");
        }

        [HttpGet("add")]
        public IActionResult AddOrder()
        {
            var locations = _locationService.GetAllLocations();
            var burgers = _burgerService.GetAllBurgers();

            ViewBag.Locations = locations.Select(l => new SelectListItem
            {
                Value = l.Id.ToString(),
                Text = l.Name
            }).ToList();

            ViewBag.Burgers = burgers.Select(b => new BurgerOrderVM
            {
                BurgerId = b.Id,
                BurgerName = b.Name,
                Quantity = 0
            }).ToList();


            return View(new CreateOrderVM());
        }



        [HttpPost("add")]
        public IActionResult AddOrder(CreateOrderVM createOrderVM)
        {
            if (ModelState.IsValid)
            {
                _orderService.AddOrder(createOrderVM);
                return RedirectToAction("Index");
            }
            foreach (var modelState in ModelState)
            {
                var key = modelState.Key;
                var errors = modelState.Value.Errors;

                foreach (var error in errors)
                {
                    Console.WriteLine($"Key: {key}, Error: {error.ErrorMessage}");
                }
            }
            var locations = _locationService.GetAllLocations();
            var burgers = _burgerService.GetAllBurgers();

            ViewBag.Locations = locations.Select(l => new SelectListItem
            {
                Value = l.Id.ToString(),
                Text = l.Name
            }).ToList();

            ViewBag.Burgers = burgers.Select(b => new BurgerOrderVM
            {
                BurgerId = b.Id,
                BurgerName = b.Name,
                Quantity = createOrderVM.BurgerOrders.FirstOrDefault(bo => bo.BurgerId == b.Id)?.Quantity ?? 0
            }).ToList();

            return View(createOrderVM);
        }

        [HttpGet("edit/{id}")]
        public IActionResult EditOrder(int id)
        {
            var locations = _locationService.GetAllLocations();
            var order = _orderService.GetOrder(id);
            var burgers = _burgerService.GetAllBurgers();

            if (order == null)
            {
                return NotFound();
            }
            ViewBag.Locations = locations.Select(l => new SelectListItem
            {
                Value = l.Id.ToString(),
                Text = l.Name
            }).ToList();
            ViewBag.Burgers = burgers.Select(b => new BurgerOrderVM
            {
                BurgerId = b.Id,
                BurgerName = b.Name,
                Quantity = 0
            }).ToList();
            var editOrderVM = new EditOrderVM
            {
                Id = order.Id,
            };
            return View(editOrderVM);
        }
        [HttpPost("edit/{id}")]
        public IActionResult EditOrder(EditOrderVM editOrderVM)
        {
            var locations = _locationService.GetAllLocations();
            var burgers = _burgerService.GetAllBurgers();
            if (ModelState.IsValid)
            {
                try
                {
                    _orderService.EditOrder(editOrderVM, editOrderVM.Id);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    ModelState.AddModelError("", "An error occurred while updating the order.");
                }
            }

            ViewBag.Locations = _locationService.GetAllLocations()
                .Select(l => new SelectListItem
                {
                    Value = l.Id.ToString(),
                    Text = l.Name
                }).ToList();
            ViewBag.Burgers = burgers.Select(b => new BurgerOrderVM
            {
                BurgerId = b.Id,
                BurgerName = b.Name,
                Quantity = editOrderVM.BurgerOrders.FirstOrDefault(bo => bo.BurgerId == b.Id)?.Quantity ?? 0
            }).ToList();
            return View("EditOrder", editOrderVM);
        }
    }
}

BurgerApp/BurgerApp.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  Best Burger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerApp.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Burger" asp-action="Index">Best Burger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Burger" asp-action="Index">Burgers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-black  text-center">
        <div class="container">
            &copy; 2024 - BurgerApp.WebApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>